name: lcov
version: 5.4.0

author: Cédric Belin <cedric@belin.io>
description: Parse and format to LCOV your code coverage reports. The best way to share your code coverage stats.
documentation: https://dev.belin.io/lcov.dart/api
homepage: https://dev.belin.io/lcov.dart
issue_tracker: https://github.com/cedx/lcov.dart/issues
repository: https://github.com/cedx/lcov.dart

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  json_annotation: ^3.0.0

dev_dependencies:
  build_runner: ^1.7.1 # 1.7.2
  build_test: ^0.10.9
  coverage: ^0.13.3
  grinder: ^0.8.3
  json_serializable: ^3.2.3
  test: ^1.9.3
