name: lcov
version: 4.1.0

author: Cédric Belin <cedric@belin.io>
description: Parse and format LCOV coverage reports.
documentation: https://cedx.github.io/lcov.dart/api
homepage: https://cedx.github.io/lcov.dart

environment:
  sdk: '>=2.0.0-dev <2.0.0'

dev_dependencies:
  coverage: ^0.10.0
  grinder: ^0.8.1
  test: ^0.12.32
