name: lcov
version: 6.0.0

description: Parse and format to LCOV your code coverage reports. The best way to share your code coverage stats.
homepage: https://docs.belin.io/lcov.dart
issue_tracker: https://git.belin.io/cedx/lcov.dart/issues
repository: https://git.belin.io/cedx/lcov.dart

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  json_annotation: ^3.1.0

dev_dependencies:
  build_runner: ^1.10.1
  build_test: ^1.2.2
  coverage: ^0.14.1
  json_serializable: ^3.5.0
  test: ^1.15.4
