name: lcov
version: 5.6.0

description: Parse and format to LCOV your code coverage reports. The best way to share your code coverage stats.
homepage: https://dev.belin.io/lcov.dart
issue_tracker: https://github.com/cedx/lcov.dart/issues
repository: https://github.com/cedx/lcov.dart

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  json_annotation: ^3.0.1

dev_dependencies:
  build_runner: ^1.7.4
  build_test: ^0.10.12
  coverage: ^0.13.6
  grinder: ^0.8.3
  json_serializable: ^3.2.5
  test: ^1.12.0
