name: lcov
version: 5.1.0

author: Cédric Belin <cedric@belin.io>
description: Parse and format to LCOV your code coverage reports. The best way to share your code coverage stats.
documentation: https://dev.belin.io/lcov.dart/api
homepage: https://dev.belin.io/lcov.dart
issue_tracker: https://github.com/cedx/lcov.dart/issues
repository: https://github.com/cedx/lcov.dart

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  json_annotation: ^2.0.0

dev_dependencies:
  build_runner: ^1.2.5
  build_test: ^0.10.6
  build_web_compilers: ^1.1.0
  coverage: ^0.12.4
  grinder: ^0.8.3
  json_serializable: ^2.0.1
  test: ^1.5.3
