name: lcov
version: 3.1.0

author: Cédric Belin <cedric@belin.io>
description: Parse and format LCOV coverage reports.
documentation: https://cedx.github.io/lcov.dart
homepage: https://github.com/cedx/lcov.dart

environment:
  sdk: '>=1.24.0 <2.0.0'

dev_dependencies:
  coverage: ^0.9.3
  grinder: ^0.8.0
  test: ^0.12.27
