name: lcov
version: 6.0.0

description: Parse and format to LCOV your code coverage reports. The best way to share your code coverage stats.
homepage: https://cedx.github.io/lcov.dart
issue_tracker: https://github.com/cedx/lcov.dart/issues
repository: https://github.com/cedx/lcov.dart
authors:
  - https://cedx.github.io/lcov.dart
  - GiKode <827266641@qq.com>

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  json_annotation: ^4.0.1

dev_dependencies:
  build_runner: ^2.0.4
  build_test: ^2.0.4
  coverage: ^1.0.3
  json_serializable: ^4.1.3
  test: ^1.17.5
