name: lcov
version: 4.4.0

author: Cédric Belin <cedric@belin.io>
description: Parse and format to LCOV your code coverage reports. The best way to share your code coverage stats.
documentation: https://dev.belin.io/lcov.dart/api
homepage: https://dev.belin.io/lcov.dart

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  json_annotation: ^1.2.0

dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.3
  build_web_compilers: ^0.4.4
  coverage: ^0.12.2
  grinder: ^0.8.3
  json_serializable: ^1.4.0
  test: ^1.3.4
