name: lcov
version: 4.1.0

author: Cédric Belin <cedric@belin.io>
description: Parse and format LCOV coverage reports.
documentation: https://dev.belin.io/lcov.dart/api
homepage: https://dev.belin.io/lcov.dart

environment:
  sdk: '>=2.0.0-dev.63 <2.0.0'

dev_dependencies:
  coverage: ^0.11.0
  grinder: ^0.8.2
  test: ^0.12.42
